# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Specifications
    url: '/specifications/'
    weight: 10

  - name: Compliance
    url: '/compliance/'
    weight: 20

  - name: Community
    url: '/community/'
    weight: 30
  - name: Contributing
    parent: Community
    url: '/community/contributing/'
    weight: 10
  - name: Roadmap
    parent: Community
    url: '/community/roadmap/'
    weight: 20
  - name: Project dashboard
    parent: Community
    url: '/project-dashboard/'
    weight: 30
  - name: Support
    parent: Community
    url: 'https://keyple-support.calypsonet.org/keyple-support/introduction/'
    weight: 35
  - name: Archives
    parent: Community
    url: '/archives/'
    weight: 40

  - name: Implementations
    url: '/implementations/'
    weight: 40


