# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Specifications
    url: '/specifications/'
    weight: 10

  - name: Roadmap
    url: '/roadmap/'
    weight: 20

  - name: Implementations
    url: '/implementations/'
    weight: 30

  - name: Dashboard
    url: '/project-dashboard/'
    weight: 40

  - name: Archives
    url: '/archives/'
    weight: 50


