@startuml

'skinparam ClassBorderColor #F1C40F
skinparam ClassBorderColor #D4AC0D
skinparam stereotypeABorderColor #A9DCDF
skinparam stereotypeIBorderColor #B4A7E5
skinparam stereotypeCBorderColor #ADD1B2
skinparam stereotypeEBorderColor #EB93DF
skinparam shadowing false

skinparam StateBorderColor #D4AC0D
skinparam ActivityBorderColor #D4AC0D

' Red
skinparam ClassBackgroundColor<<red>> #FDEDEC
skinparam ClassBorderColor<<red>> #E74C3C
hide <<red>> stereotype
' Purple
skinparam ClassBackgroundColor<<purple>> #F4ECF7
skinparam ClassBorderColor<<purple>> #8E44AD
hide <<purple>> stereotype
' blue
skinparam ClassBackgroundColor<<blue>> #EBF5FB
skinparam ClassBorderColor<<blue>> #3498DB
hide <<blue>> stereotype
' Green
skinparam ClassBackgroundColor<<green>> #EAFAF1
skinparam ClassBorderColor<<green>> #2ECC71
hide <<green>> stereotype

' Orange
skinparam ClassBackgroundColor<<orange>> #FDF2E9
skinparam ClassBorderColor<<orange>> #E67E22
hide <<orange>> stereotype

' Grey
skinparam ClassBackgroundColor<<grey>> #EAECEE
skinparam ClassBorderColor<<grey>> #2C3E50
hide <<grey>> stereotype

actor "Ticketing Application" as app #gold
participant "Calypso API" as capi #pink
participant "Reader API" as rapi #pink
participant "Calypso Card\nReader" as cardReader #lightBlue
boundary "**Card**" as card #lightBlue
participant "Calypso SAM\nReader" as samReader #lightGreen
boundary "selected\n**SAM**" as sam #lightGreen

activate app #gold
activate sam #lightGreen

== Card selection & identification ==

note over capi
    Only reads data inside the session.
end note

app->capi: <font color=red>**prepare**</font> card selection scenario:\n\t- filter by specific AID\n\t- filter invalidated card status
activate capi  #pink
capi-->app
deactivate capi

app->rapi: <font color=red>**process**</font> explicit card selection scenario
activate rapi  #pink
rapi-[#0000FF]>cardReader: <font color=blue>**Card #1**</font>\ntransmit selection request\n\t- card selector
activate cardReader #lightBlue

cardReader->card: open card channel
activate card #lightBlue
card-->cardReader
cardReader->card: select application (aid)
card-->cardReader: [card FCI]
cardReader->cardReader: checks invalidation status

cardReader--[#0000FF]>rapi: receive selection response
deactivate cardReader

rapi-->app: selected active SmartCard image
deactivate rapi

app->capi: **cast** Calypso card
activate capi  #pink
capi-->app: [Calypso card image:\n\t- identification data\n\t- invalidation status]

deactivate capi

== Card secure transaction ==

app->app: **instantiate** Calypso card transaction:\n\t- Calypso card resource\n\t- Calypso SAM resource

app->capi: <font color=red>**prepare**</font> card transaction:\n\t- open secure session (DEBIT access level)\n\t- read environment file
activate capi  #pink
capi-->app
deactivate capi

app->capi: <font color=red>**process**</font> commands (keep channel open)
activate capi  #pink

capi-[#00FF00]>samReader: <font color=green>**SAM #1**<font color=red>\ntransmit card request\n\t- APDU list
activate samReader #lightGreen
samReader->sam: get challenge
sam-->samReader: [SAM challenge]
samReader-[#00FF00]->capi: [SAM challenge]
deactivate samReader

capi-[#0000FF]>cardReader: <font color=blue>**Card #2**</font>\ntransmit card request\n\t- APDU list
activate cardReader #lightBlue

group Card APDU commands inside session
note over cardReader
    Optimization: environment file read through the session opening.
end note

    cardReader->card: open secure session (card debit key,\n\tSAM challenge,\n\tSFI environment to read)
    card-->cardReader: [card challenge & environment data]
end

cardReader--[#0000FF]>capi: [card challenge]
deactivate cardReader
capi->capi: checks ratification status

capi-->app: [Calypso card image:\n\t- identification data\n\t- invalidation status\n\t- environment data\n\t- ratification status]
deactivate capi

app->app: checks support of extended modes\n - if supported initial authentication

app->capi: <font color=red>**prepare**</font> card transaction:\n\t- manage session for authentication
activate capi  #pink
capi-->app
deactivate capi

app->capi: <font color=red>**process**</font> commands (keep channel open)
activate capi  #pink

capi-[#00FF00]>samReader: <font color=green>**SAM #2**<font color=red>\ntransmit card request\n\t- APDU list
activate samReader #lightGreen
samReader->sam: select diversifier (card serial)
sam-->samReader
samReader->sam: digest init (opening data)
sam-->samReader

group#AliceBlue #AliceBlue Initial Authentication

samReader->sam: digest internal authenticate
sam-->samReader: [SAM certificate]
samReader-[#00FF00]->capi: [SAM certificate]
deactivate samReader

capi-[#0000FF]>cardReader: <font color=blue>**Card #3**</font>\ntransmit card request\n\t- APDU list
activate cardReader #lightBlue

note over cardReader
    command outside of the SMAC (no Digest Update)
end note

    cardReader->card: manage secure session (authentication on, encryption off,\n\tSAM certificate)
    card-->cardReader: [card certificate]

cardReader--[#0000FF]>capi: [card challenge]
deactivate cardReader

capi-[#00FF00]>samReader: <font color=green>**SAM #3**<font color=red>\ntransmit card request\n\t- APDU list
activate samReader #lightGreen
samReader->sam: digest authenticate (card certificate)
sam-->samReader: [authentication status]
samReader-[#00FF00]->capi: [authentication status]
deactivate samReader

end

capi-->app: [Calypso card image:\n\t- identification data\n\t- invalidation status\n\t- environment data\n\t- ratification status\n\t- authentication status]
deactivate capi

app->capi: <font color=red>**prepare**</font> card transaction:\n\t- read last event
activate capi  #pink
capi-->app
deactivate capi

app->capi: <font color=red>**process**</font> commands (keep channel open)
activate capi  #pink

capi-[#0000FF]>cardReader: <font color=blue>**Card #4**</font>\ntransmit card request\n\t- APDU list
activate cardReader #lightBlue

group Card APDU commands inside session
    cardReader->card: read record (last event)
    card-->cardReader: [last event data]
end

cardReader--[#0000FF]>capi: [last event data]
deactivate cardReader

capi-->app: [Calypso card image:\n\t- identification data\n\t- invalidation status\n\t- environment data\n\t- ratification status\n\t- last event data]
deactivate capi

app->app: checks transaction recovery status

app->capi: <font color=red>**prepare**</font> card transaction:\n\t- read contract list
activate capi  #pink
capi-->app
deactivate capi

app->capi: <font color=red>**process**</font> commands (keep channel open)
activate capi  #pink

capi-[#0000FF]>cardReader: <font color=blue>**Card #5**</font>\ntransmit card request\n\t- APDU list
activate cardReader #lightBlue

group Card APDU commands inside session
    cardReader->card: read record (contract list)
    card-->cardReader: [contract list data]
end

cardReader--[#0000FF]>capi: [contract list data]
deactivate cardReader

capi-->app: [Calypso card image:\n\t- identification data\n\t- invalidation status\n\t- environment data\n\t- ratification status\n\t- last event data\n\t- contract list data]
deactivate capi

app->app: identifies contract

app->capi: <font color=red>**prepare**</font> card transaction:\n\t- read contract #x
activate capi  #pink
capi-->app
deactivate capi

app->capi: <font color=red>**process**</font> commands (keep channel open)
activate capi  #pink

capi-[#0000FF]>cardReader: <font color=blue>**Card #6**</font>\ntransmit card request\n\t- APDU list
activate cardReader #lightBlue

group Card APDU commands inside session
    cardReader->card: read record (contract #x)
    card-->cardReader: [contract #x data]
end

cardReader--[#0000FF]>capi: [contract #x data]
deactivate cardReader

capi-->app: [Calypso card image:\n\t- identification data\n\t- invalidation status\n\t- environment data\n\t- ratification status\n\t- last event data\n\t- contract list data\n\t- contract #x data]
deactivate capi

app->app: identifies associated counter

app->capi: <font color=red>**prepare**</font> card transaction:\n\t- reader counter #x
activate capi  #pink
capi-->app
deactivate capi

app->capi: <font color=red>**process**</font> commands (keep channel open)
activate capi  #pink

capi-[#0000FF]>cardReader: <font color=blue>**Card #7**</font>\ntransmit card request\n\t- APDU list
activate cardReader #lightBlue

group Card APDU commands inside session
    cardReader->card: read record (counter #x)
    card-->cardReader: [counter #x data]
end

cardReader--[#0000FF]>capi: [counter #x data]
deactivate cardReader

capi-->app: [Calypso card image:\n\t- identification data\n\t- invalidation status\n\t- environment data\n\t- ratification status\n\t- last event data\n\t- contract list data\n\t- contract #x data\n\t- counter #x data]
deactivate capi

app->app: defines data to update

app->capi: <font color=red>**prepare**</font>:\n\t- decrease counter #x (new value)\n\t- append event record (new event)\n\t- close secure session (not ratified)
activate capi  #pink

capi-->app
deactivate capi

app->capi: <font color=red>**process**</font> commands (close channel after)
activate capi  #pink
capi->capi: anticipates the future card responses
note over capi
    If the current value of the counter #x were **unknown**, then the transmission of an additional card APDU
    message would be necessary to operate the decrease counter in a different message than the session closing.
end note

capi-[#00FF00]>samReader: <font color=green>**SAM #4**</font>\ntransmit card request\n\t- APDU list
activate samReader #lightGreen

samReader->sam: digest update (read environment) * 2
sam-->samReader
samReader->sam: digest update (last event) * 2
sam-->samReader
samReader->sam: digest update (read contract list) * 2
sam-->samReader
samReader->sam: digest update (read contract #x) * 2
sam-->samReader
samReader->sam: digest update (read counters) * 2
sam-->samReader
group <font color=red>**anticipated**</font> Card APDU responses
    samReader->sam: digest update (decrease counter) * 2
    sam-->samReader
    samReader->sam: digest update (append event record) * 2
    sam-->samReader
end
samReader->sam: digest close
sam-->samReader: [SAM certificate]

samReader-[#00FF00]->capi: [SAM certificate]
deactivate samReader

capi-[#0000FF]>cardReader: <font color=blue>**Card #8**</font>\ntransmit card request\n\t- APDU list
activate cardReader #lightBlue

group Card APDU commands inside session
    cardReader->card: decrease counter (counter #1, value)
    card-->cardReader: [new counter value]
    cardReader->card: append record (event, data)
    card-->cardReader
end

cardReader->card: close secure session (SAM certificate, as non ratified)
card-->cardReader: [card certificate]
cardReader->card: ratification command
card-->cardReader
cardReader->card: close card channel
card-->cardReader
deactivate card

cardReader-[#0000FF]->capi: [card certificate]
deactivate cardReader

capi-[#00FF00]>samReader: <font color=green>**SAM #5**</font>\ntransmit card request\n\t- APDU list
activate samReader #lightGreen
samReader->sam: digest authenticate (card certificate)
sam-->samReader: [authentication status]

samReader-[#00FF00]->capi: [authentification status]
deactivate samReader

capi-->app: [Calypso card image:\n\t- identification data\n\t- invalidation status\n\t- environment data\n\t- --ratification status--\n\t- last event data (updated)\n\t- contract list data\n\t- contract #x data\n\t- counter #x data (updated)]\nauthentification status
deactivate capi
@enduml